name: 'Lint PR'
description: 'Lints a submitted Github pull request and outputs via comment'
author: 'Yuri Bocharov'
inputs:
  message:
    description: 'Message that should be printed in the pull request'
  file-path:
    description: 'Path of the file that should be commented'
  github-token:
    description:
      'Github token of the repository (automatically created by Github)'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
